{
 "title": "Jupyterhub SLI/SLO",
 "tags": [ "SRE" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "error_codes",
    "query": "label_values(request_duration_seconds_count{job=\"JupyterHub Metrics\"},code)"
   },
   {
    "name": "handler",
    "query": "label_values(request_duration_seconds_count,handler)"
   },
   {
    "name": "kerberos_id",
    "label": "Kerberos ID",
    "query": "kubelet_volume_stats_used_bytes{namespace='dh-prod-jupyterhub'}"
   },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_usage_seconds_total,namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "![jupyterhubimage](https://avatars0.githubusercontent.com/u/17927519?s=200&v=4)"
   },
   "content": "![jupyterhubimage](https://avatars0.githubusercontent.com/u/17927519?s=200&v=4)"
  },
  {
   "title": "Pods Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod_name=~\".*jupyterhub-nb.*\"}) by(pod_name))"
    }
   ]
  },
  {
   "title": "GPU enabled Pods",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_accelerator_duty_cycle{pod_name=~\".*jupyterhub-nb.*\"})"
    }
   ]
  },
  { "title": "SLI: Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{service=\"jupyterhub\"}"
    }
   ]
  },
  {
   "title": "JupyterHub Startup Time",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 10 },
   "options": {
    "content": "# JupyterHub Startup time\nIn v1.2.1 there is a new metric `hub_startup_duration_seconds`which measures time taken for the Hub to start. This might be useful in calculating avg. startup time and measuring availability."
   },
   "content": "# JupyterHub Startup time\nIn v1.2.1 there is a new metric `hub_startup_duration_seconds`which measures time taken for the Hub to start. This might be useful in calculating avg. startup time and measuring availability."
  },
  {
   "title": "User Activity",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "options": {
    "content": "New metrics for tracking user activity in v1.2.1:\n\n`total_users` -  Total number of users\n\n`running_servers` -  The number of user servers currently running"
   },
   "content": "New metrics for tracking user activity in v1.2.1:\n\n`total_users` -  Total number of users\n\n`running_servers` -  The number of user servers currently running"
  },
  { "title": "SLI: Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Server Spawn Operations",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_spawn_duration_seconds_count{job=\"JupyterHub Metrics\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hub Pod Restart Count",
   "type": "graph",
   "gridPos": { "h": 15, "w": 4, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"jupyterhub-nb.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_duration_seconds_count{job=\"JupyterHub Metrics\", code=\"$error_codes\", method=\"GET\"}"
    },
    {}
   ]
  },
  {
   "title": "JupyterHub Notebook Servers Fail Rate",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(server_spawn_duration_seconds_count{status=\"failure\"}[5m])"
    },
    {}
   ]
  },
  { "title": "SLI: Quality & Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "JupyterHub CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\".*jupyter.*\"}[2m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Jupyterhub Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod_name=~\".*jupyter.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "JupyterHub Storage Capacity for  $kerberos_id",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace='$namespace',persistentvolumeclaim=~\".*$kerberos_id.*\"}/kubelet_volume_stats_capacity_bytes{namespace='$namespace',persistentvolumeclaim=~\".*$kerberos_id.*\"}"
    }
   ]
  },
  { "title": "Kube Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "OOMKilled Pods (needs to be modified)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kube_pod_container_status_terminated_reason{namespace=\"$namespace\", pod=~\"jupyterhub-nb-.*\", reason=\"OOMKilled\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Creation Errors",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting_reason{namespace=\"$namespace\",pod=~\"jupyterhub-nb-.*\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff\"} == 1) by(reason,pod)"
    }
   ]
  }
 ]
}