{
 "title": "OperateFirst Availability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Monitoring Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service=\"prometheus-operated\", pod=~\"prometheus-odh-monitoring.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alertmanager",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service=\"alert-manager\"}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service=~\"grafana-.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "JupyterHub",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service=\"jupyterhub\"}"
    }
   ]
  },
  {
   "title": "Argo Workflow Controller",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service=\"workflow-controller-metrics\"}"
    }
   ]
  },
  { "title": "Observatorium Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Observatorium",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{service=~\"opf-observatorium-loki-.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}